-- =============================================================================
-- Permix — reference data
-- Idempotent: safe to re-run after a schema reset.
-- =============================================================================

insert into public.wilayas (code, name_ar, name_fr, name_en) values
  (1,  'أدرار',            'Adrar',              'Adrar'),
  (2,  'الشلف',            'Chlef',              'Chlef'),
  (3,  'الأغواط',          'Laghouat',           'Laghouat'),
  (4,  'أم البواقي',       'Oum El Bouaghi',     'Oum El Bouaghi'),
  (5,  'باتنة',            'Batna',              'Batna'),
  (6,  'بجاية',            'Béjaïa',             'Bejaia'),
  (7,  'بسكرة',            'Biskra',             'Biskra'),
  (8,  'بشار',             'Béchar',             'Bechar'),
  (9,  'البليدة',          'Blida',              'Blida'),
  (10, 'البويرة',          'Bouira',             'Bouira'),
  (11, 'تمنراست',          'Tamanrasset',        'Tamanrasset'),
  (12, 'تبسة',             'Tébessa',            'Tebessa'),
  (13, 'تلمسان',           'Tlemcen',            'Tlemcen'),
  (14, 'تيارت',            'Tiaret',             'Tiaret'),
  (15, 'تيزي وزو',         'Tizi Ouzou',         'Tizi Ouzou'),
  (16, 'الجزائر',          'Alger',              'Algiers'),
  (17, 'الجلفة',           'Djelfa',             'Djelfa'),
  (18, 'جيجل',             'Jijel',              'Jijel'),
  (19, 'سطيف',             'Sétif',              'Setif'),
  (20, 'سعيدة',            'Saïda',              'Saida'),
  (21, 'سكيكدة',           'Skikda',             'Skikda'),
  (22, 'سيدي بلعباس',      'Sidi Bel Abbès',     'Sidi Bel Abbes'),
  (23, 'عنابة',            'Annaba',             'Annaba'),
  (24, 'قالمة',            'Guelma',             'Guelma'),
  (25, 'قسنطينة',          'Constantine',        'Constantine'),
  (26, 'المدية',           'Médéa',              'Medea'),
  (27, 'مستغانم',          'Mostaganem',         'Mostaganem'),
  (28, 'المسيلة',          'M''Sila',            'MSila'),
  (29, 'معسكر',            'Mascara',            'Mascara'),
  (30, 'ورقلة',            'Ouargla',            'Ouargla'),
  (31, 'وهران',            'Oran',               'Oran'),
  (32, 'البيض',            'El Bayadh',          'El Bayadh'),
  (33, 'إليزي',            'Illizi',             'Illizi'),
  (34, 'برج بوعريريج',     'Bordj Bou Arréridj', 'Bordj Bou Arreridj'),
  (35, 'بومرداس',          'Boumerdès',          'Boumerdes'),
  (36, 'الطارف',           'El Tarf',            'El Tarf'),
  (37, 'تندوف',            'Tindouf',            'Tindouf'),
  (38, 'تيسمسيلت',         'Tissemsilt',         'Tissemsilt'),
  (39, 'الوادي',           'El Oued',            'El Oued'),
  (40, 'خنشلة',            'Khenchela',          'Khenchela'),
  (41, 'سوق أهراس',        'Souk Ahras',         'Souk Ahras'),
  (42, 'تيبازة',           'Tipaza',             'Tipaza'),
  (43, 'ميلة',             'Mila',               'Mila'),
  (44, 'عين الدفلى',       'Aïn Defla',          'Ain Defla'),
  (45, 'النعامة',          'Naâma',              'Naama'),
  (46, 'عين تموشنت',       'Aïn Témouchent',     'Ain Temouchent'),
  (47, 'غرداية',           'Ghardaïa',           'Ghardaia'),
  (48, 'غليزان',           'Relizane',           'Relizane'),
  (49, 'تيميمون',          'Timimoun',           'Timimoun'),
  (50, 'برج باجي مختار',   'Bordj Badji Mokhtar','Bordj Badji Mokhtar'),
  (51, 'أولاد جلال',       'Ouled Djellal',      'Ouled Djellal'),
  (52, 'بني عباس',         'Béni Abbès',         'Beni Abbes'),
  (53, 'عين صالح',         'In Salah',           'In Salah'),
  (54, 'عين قزام',         'In Guezzam',         'In Guezzam'),
  (55, 'تقرت',             'Touggourt',          'Touggourt'),
  (56, 'جانت',             'Djanet',             'Djanet'),
  (57, 'المغير',           'El M''Ghair',        'El MGhair'),
  (58, 'المنيعة',          'El Meniaa',          'El Meniaa')
on conflict (code) do update
  set name_ar = excluded.name_ar,
      name_fr = excluded.name_fr,
      name_en = excluded.name_en;

-- Algerian licence categories.
insert into public.categories (code, label_ar, label_fr, label_en, sort_order) values
  ('A1', 'دراجات نارية أقل من 125 سم³', 'Motocycles jusqu''à 125 cm³',       'Motorcycles up to 125 cc',   10),
  ('A2', 'دراجات نارية أكثر من 125 سم³','Motocycles de plus de 125 cm³',     'Motorcycles above 125 cc',   20),
  ('B',  'سيارات خفيفة',                'Véhicules légers',                  'Light vehicles',             30),
  ('C',  'شاحنات نقل البضائع',          'Poids lourds — marchandises',       'Heavy goods vehicles',       40),
  ('D',  'نقل الأشخاص',                 'Transport en commun de personnes',  'Passenger transport',        50),
  ('E',  'المقطورات',                   'Remorques',                         'Trailers',                   60),
  ('F',  'مركبات مهيأة لذوي الإعاقة',   'Véhicules aménagés (handicap)',     'Adapted vehicles',           70)
on conflict (code) do update
  set label_ar   = excluded.label_ar,
      label_fr   = excluded.label_fr,
      label_en   = excluded.label_en,
      sort_order = excluded.sort_order;
